Znieh\Model\Unit:
  exclusion_policy: ALL
  properties:
    name:
      expose: true
    weapon:
      expose: true
    armor:
      expose: true
    physical:
      expose: true
    size:
      expose: true
  virtual_properties:
    getPoints:
      serialized_name: points
      type: integer
    getMoves:
      serialized_name: moves
      type: integer
    getWeight:
      serialized_name: weight
      type: integer
