Znieh\Model\Unit:
  exclusion_policy: ALL
  properties:
    name:
      expose: true
    weapon:
      expose: true
    armor:
      expose: true
    weight:
      expose: true
    size:
      expose: true
  virtual_properties:
    getPoints:
      serialized_name: points
      type: integer
