Znieh\Model\WeaponPartType:
    type:  entity
    table: weapon_part_types
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
