Znieh\Model\Weight:
    type:  entity
    table: weight
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      name:
        type: string
        length: 255
